version: '3'
services:
  pupeteer:
    hostname: pupeteer
    container_name: pupeteer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OUTPUT_FILE=${OUTPUT_FILE}
        - HOMEASSISTANT_LOGIN_USER=${HOMEASSISTANT_LOGIN_USER}
        - HOMEASSISTANT_LOGIN_PASS=${HOMEASSISTANT_LOGIN_PASS}
        - HOMEASSISTANT_URL=${HOMEASSISTANT_URL}
        - SLEEP=${SLEEP}
    env_file:
    - .env
    restart: always